### ISSUE TITLE
java is not recognized

### ISSUE THREAD

**Issue by Roxy68** [EGSilver/raidSorter#1]
Both 10 and 25 batch files stat java is not recognized

![image](https://user-images.githubusercontent.com/52102649/198830714-76078e40-c5cb-4082-97ab-5ee17c1fd80e.png)

**Comment by EGSilver** [comment]
You need to install java on your machine.
https://java.com

**Comment by EGSilver** [comment]
> Both 10 and 25 batch files stat java is not recognized
> 
> ![image](https://user-images.githubusercontent.com/52102649/198830714-76078e40-c5cb-4082-97ab-5ee17c1fd80e.png)

You need to install java on your machine.
https://www.oracle.com/java/technologies/downloads/
